server:
  context-path: /
logging.level.org.springframework.web: INFO

spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:~/main
      username: user
      password:
      driver-class-name: org.h2.Driver

app:
  urls:
    geolocation: http://ip-api.com/json
    weather: https://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&units=metric&appid=b51859ba8571005d0192e1f9bff694a6